version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: not_root_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql